### ISSUE TITLE
Error while building program with cargo build-bpf

### ISSUE THREAD

**Issue by anoushk1234** [Unboxed-Software/solana-course#128]
<img width="894" alt="Screenshot 2022-08-15 at 12 16 32 PM" src="https://user-images.githubusercontent.com/32778608/184588894-3c118373-a4c7-432e-a0da-774fe93eca70.png">

```
BPF SDK: /home/ubuntu/.local/share/solana/install/releases/1.10.31/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
/home/ubuntu/.rustup/toolchains/bpf/bin/cargo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

```toml
[package]
name = "sdc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
no-entrypoint = []

[dependencies]
solana-program = "1.10.31"

[lib]
crate-type = ["cdylib", "lib"]

```
